/*
 * clCoordTransDialog.java
 *
 * Created on 7. June 2004
 */

package Fachwerk.addins.skaliereLasten;

import java.util.*;

/**
 * Fachwerk - treillis
 *
 * Copyright (c) 2004 - 2009 A.Vontobel <qwert2003@users.sourceforge.net>
 *                                      <qwert2003@users.berlios.de>
 *
 * Das Programm könnte FEHLER enthalten. Sämtliche Resultate sind
 * SORGFÄLTIG auf ihre PLAUSIBILITäT zu prüfen!
 *
 * Dieses einfache Fachwerkprogramm verwendet ausschliesslich die
 * Gleichgewichtsbedingungen zur Bestimmung der Stabkräfte.
 * Bei statisch unbestimmten Systemen können die überzähligen Stabkräfte
 * zugewiesen werden.
 * Das Programm bezweckt, die Anwendung des unteren (statischen)
 * Grenzwertsatzes der Plastizitätstheorie zu erleichtern.
 *
 * -------------------------------------------------------------
 *
 * Dieses Programm ist freie Software. Sie können es unter den Bedingungen
 * der GNU General Public License, Version 2, wie von der Free Software
 * Foundation herausgegeben, weitergeben und/oder modifizieren.
 *
 * Die Veröffentlichung dieses Programms erfolgt in der Hoffnung, dass es
 * Ihnen von Nutzen sein wird, aber OHNE JEDE GEWÄHRLEISTUNG - sogar ohne
 * die implizite Gewährleistung der MARKTREIFE oder der EIGNUNG FüR EINEN
 * BESTIMMTEN ZWECK.  Details finden Sie in der GNU General Public License.
 *
 * Sie sollten eine Kopie der GNU General Public License zusammen  mit
 * diesem Programm erhalten haben. Falls nicht, schreiben Sie an die
 * Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA.
 */
public class clguiLastenSkalieren extends javax.swing.JDialog {
        
    private double faktor = 1;
    private boolean INKLSTABKRÄFTE = true;
    private String einleitung;
    boolean OK = false;
    ResourceBundle dialogRB;
    Locale locale;
    
    /** Lasten Skalieren Dialog*/
    public clguiLastenSkalieren(java.awt.Frame parent, String titel, Locale lc) {
        super(parent, titel, true);
        locale = lc;
        
        initComponents();
        // übersetzen
        dialogRB = ResourceBundle.getBundle("Fachwerk/locales/gui-dialoge", locale);
        if (dialogRB == null) {
            System.err.println("FEHLER: gui-dialoge für " + locale.toString());
            return;
        }
        else {
            knopfAbbruch.setText(tr("Abbruch"));
            knopfOK.setText(tr("OK"));
        }
        
        dialogRB = ResourceBundle.getBundle("Fachwerk/locales/gui-addins", locale);
        if (dialogRB == null) {
            System.err.println("FEHLER: gui-addins für " + locale.toString());
            return;
        }
        else {
            jLabel1.setText(tr("lb-Lastenskalieren"));
            jLabel1.setToolTipText(tr("ttip-Lastenskalieren"));
            checkbox_inklStaebe.setText(tr("checkbox-Stabkraefte"));
            checkbox_inklStaebe.setToolTipText(tr("ttip-Stabkraefte"));
        }
        
        pack();
        zentriere(parent);
        setVisible(true);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        knopfOK = new javax.swing.JButton();
        knopfAbbruch = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btMal = new javax.swing.JRadioButton();
        btDurch = new javax.swing.JRadioButton();
        feldFaktor = new javax.swing.JTextField();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel5 = new javax.swing.JPanel();
        checkbox_inklStaebe = new javax.swing.JCheckBox();
        lbEinleitung = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        knopfOK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fachwerk/gui/icons/button_ok.png")));
        knopfOK.setText("OK !");
        knopfOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                knopfOKActionPerformed(evt);
            }
        });

        jPanel1.add(knopfOK);

        knopfAbbruch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fachwerk/gui/icons/button_cancel.png")));
        knopfAbbruch.setText("Abbruch");
        knopfAbbruch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                knopfAbbruchActionPerformed(evt);
            }
        });

        jPanel1.add(knopfAbbruch);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        jPanel2.setLayout(new java.awt.GridLayout(3, 2));

        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Lasten skalieren");
        jLabel1.setToolTipText("Multipliziert alle Lasten mit einem Faktor.");
        jPanel4.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel4);

        jPanel6.setLayout(new java.awt.BorderLayout());

        buttonGroup1.add(btMal);
        btMal.setSelected(true);
        btMal.setText("*");
        jPanel6.add(btMal, java.awt.BorderLayout.CENTER);

        buttonGroup1.add(btDurch);
        btDurch.setText("/");
        jPanel6.add(btDurch, java.awt.BorderLayout.SOUTH);

        jPanel3.add(jPanel6);

        feldFaktor.setColumns(3);
        feldFaktor.setText("1");
        feldFaktor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feldFaktorActionPerformed(evt);
            }
        });

        jPanel3.add(feldFaktor);

        jPanel3.add(jDesktopPane1);

        jPanel2.add(jPanel3);

        checkbox_inklStaebe.setSelected(true);
        checkbox_inklStaebe.setText("auch Stabkr\u00e4fte skalieren");
        checkbox_inklStaebe.setToolTipText("Skaliert auch die gesetzten Stabkr\u00e4fte");
        jPanel5.add(checkbox_inklStaebe);

        jPanel2.add(jPanel5);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        lbEinleitung.setText(einleitung);
        getContentPane().add(lbEinleitung, java.awt.BorderLayout.NORTH);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents

    private void feldFaktorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feldFaktorActionPerformed
        try{
            double eingabefaktor = Double.parseDouble(feldFaktor.getText());
            if (Math.abs(eingabefaktor) < 1E-9) {
                System.out.println("Faktor < 1E-9");
                feldFaktor.setSelectionStart(0); feldFaktor.setSelectionEnd(feldFaktor.getText().length());
            }
        }
        catch (NumberFormatException e) {
            System.out.println(e.toString());
            feldFaktor.setSelectionStart(0); feldFaktor.setSelectionEnd(feldFaktor.getText().length());
        }
    }//GEN-LAST:event_feldFaktorActionPerformed

    private void knopfAbbruchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_knopfAbbruchActionPerformed
        OK = false;
        setVisible(false);
    }//GEN-LAST:event_knopfAbbruchActionPerformed

    private void knopfOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_knopfOKActionPerformed
        if (einlesen()) {
            OK = true;
            setVisible(false);
        }
    }//GEN-LAST:event_knopfOKActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        OK = false;
        setVisible(false);
    }//GEN-LAST:event_closeDialog
   
    private boolean einlesen() {
        double eingabefaktor;
        
        // Faktor
        try{
            eingabefaktor = Double.parseDouble(feldFaktor.getText());
            if (Math.abs(eingabefaktor) < 1E-6) {
                System.out.println("|Faktor| <  1E-6");
                feldFaktor.selectAll();
                return false;
            }
            if (Math.abs(eingabefaktor) > 1E+6) {
                System.out.println("|Faktor| >  1E+6");
                feldFaktor.selectAll();
                return false;
            }
        }
        catch (NumberFormatException e) {
            System.out.println(e.toString());
            feldFaktor.selectAll();
            return false;
        }
        
        if (btDurch.isSelected()) {
            faktor = 1d/eingabefaktor;
        }
        else {
            assert btMal.isSelected();
            faktor = eingabefaktor;
        }
        
        // Auch Stabkräfte skalieren?
        INKLSTABKRÄFTE = checkbox_inklStaebe.isSelected();
        
        return true;
    }
    
    /** Gibt den eingegebenen Skalierungsfaktor zurück. Bei einem Dialogabbruch: 1
     @returns Faktor*/
    public double getAntwort_Faktor() {
        if (OK) {
            double antwort = faktor;
            return antwort;
        }
        else return 1.0;
    }
    
    /** Gibt an, ob auch die gesetzten Stabkräfte skaliert werden sollen.
     @returns INKLSTABKRÄFTE*/
    public boolean getAntwort_inklStäbe() {
        return INKLSTABKRÄFTE;
    }
    
    private void zentriere(java.awt.Frame hf) {
        java.awt.Point OL = hf.getLocationOnScreen();
        OL.translate(hf.getWidth()/2, hf.getHeight()/2);
        OL.translate(-this.getWidth()/2, -this.getHeight()/2);
        if (OL.getX() < 0) OL.setLocation(0, OL.getY());
        if (OL.getY() < 0) OL.setLocation(OL.getX(), 0);
        this.setLocation(OL);
    }
    
    private String tr(String key) {
        String übersetzt;
        try {übersetzt = dialogRB.getString(key);}
        catch (MissingResourceException e) {
            System.err.println("Schluesselwort + " + key + " nicht gefunden fuer " + locale.toString() + " ; " + e.toString());
            return key;
        }
        return übersetzt;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btDurch;
    private javax.swing.JRadioButton btMal;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox checkbox_inklStaebe;
    private javax.swing.JTextField feldFaktor;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JButton knopfAbbruch;
    private javax.swing.JButton knopfOK;
    private javax.swing.JLabel lbEinleitung;
    // End of variables declaration//GEN-END:variables
    
}
