/*
 * clOK.java
 *
 * Created on 8. September 2003, 21:06
 */

package Fachwerk.gui;
import java.util.*;
/**
 * GPL
 * @author  av  <qwert2003@users.berlios.de>
 */
public class clOK extends javax.swing.JDialog {
    
    private String text;
    private boolean antwort = false;
    ResourceBundle dialogRB;
    Locale locale;
    
    /** Creates new form testDialog */
    public clOK(java.awt.Frame parent, String titel, String fragetext, Locale lc) {        
        super(parent, titel, true); // Dialog immer modal
        text = fragetext;
        initComponents();
        // übersetzen
        locale = lc;
        dialogRB = ResourceBundle.getBundle("Fachwerk/locales/gui-dialoge", locale);
        if (dialogRB == null) {
            System.err.println("FEHLER: gui-dialoge für " + locale.toString());
        }
        knopfOK.setText(tr("OK"));        
        knopfAbbrechen.setText(tr("zurueck"));
        infoFeld.setColumns((int)(fragetext.length()/1.45));
        tastenbelegen();
        pack();
        zentriere(parent);
        show();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        infoFeld = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        knopfOK = new javax.swing.JButton();
        knopfAbbrechen = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        infoFeld.setEditable(false);
        infoFeld.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        infoFeld.setText(text);
        infoFeld.setPreferredSize(new java.awt.Dimension(200, 50));
        getContentPane().add(infoFeld, java.awt.BorderLayout.CENTER);

        knopfOK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fachwerk/gui/icons/button_ok.png")));
        knopfOK.setText("OK !");
        knopfOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                knopfOKActionPerformed(evt);
            }
        });

        jPanel1.add(knopfOK);

        knopfAbbrechen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fachwerk/gui/icons/button_cancel.png")));
        knopfAbbrechen.setText("Lieber unverrichteter Dinge zur\u00fcck.");
        knopfAbbrechen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                knopfAbbrechenActionPerformed(evt);
            }
        });

        jPanel1.add(knopfAbbrechen);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        pack();
    }//GEN-END:initComponents

    private void knopfAbbrechenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_knopfAbbrechenActionPerformed
        antwort = false;
        setVisible(false);
    }//GEN-LAST:event_knopfAbbrechenActionPerformed

    private void knopfOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_knopfOKActionPerformed
        antwort = true;
        setVisible(false);
    }//GEN-LAST:event_knopfOKActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        //dispose();
    }//GEN-LAST:event_closeDialog
    
    public boolean ok() {
        return antwort;
    }
    
    private void tastenbelegen() {                
        javax.swing.ActionMap am = getRootPane().getActionMap();
        javax.swing.InputMap im = getRootPane().getInputMap(javax.swing.JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        
        // ESC - Taste
        Object EscapeObjekt = new Object();
        javax.swing.KeyStroke EscapeStroke = javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0);
        javax.swing.Action EscapeAction = new javax.swing.AbstractAction() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                antwort = false;              // Befehl
                setVisible(false);
            }
        };
        im.put(EscapeStroke, EscapeObjekt);
        am.put(EscapeObjekt, EscapeAction);
        
        // ENTER - Taste
        Object EnterObjekt = new Object();
        javax.swing.KeyStroke EnterStroke = javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, 0);
        javax.swing.Action EnterAction = new javax.swing.AbstractAction() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                antwort = true;               // Befehl
                setVisible(false);
            }
        };
        im.put(EnterStroke, EnterObjekt);
        am.put(EnterObjekt, EnterAction);
    }
    
    private void zentriere(java.awt.Frame hf) {
        java.awt.Point OL = hf.getLocationOnScreen();
        OL.translate(hf.getWidth()/2, hf.getHeight()/2);
        OL.translate(-this.getWidth()/2, -this.getHeight()/2);
        if (OL.getX() < 0) OL.setLocation(0, OL.getY());
        if (OL.getY() < 0) OL.setLocation(OL.getX(), 0);
        this.setLocation(OL);
    }
    
    private String tr(String key) {        
        String übersetzt;
        try {übersetzt = dialogRB.getString(key);}
        catch (MissingResourceException e) {
            System.err.println("Schluesselwort + " + key + " nicht gefunden fuer " + locale.toString() + " ; " + e.toString());
            return key;
        }        
        return übersetzt;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField infoFeld;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton knopfAbbrechen;
    private javax.swing.JButton knopfOK;
    // End of variables declaration//GEN-END:variables
    
}
