/*
 * clWählenDialog.java
 *
 * Created on 9. September 2003, 22:06
 */

package Fachwerk.gui;

import Fachwerk.statik.*;
import java.util.*;

/**
 * Fachwerk - treillis
 *
 * Copyright (c) 2003 - 2009 A.Vontobel <qwert2003@users.sourceforge.net>
 *                                      <qwert2003@users.berlios.de>
 *
 * Das Programm könnte FEHLER enthalten. Sämtliche Resultate sind
 * SORGFÄLTIG auf ihre PLAUSIBILITäT zu prüfen!
 *
 * Dieses einfache Fachwerkprogramm verwendet ausschliesslich die
 * Gleichgewichtsbedingungen zur Bestimmung der Stabkräfte.
 * Bei statisch unbestimmten Systemen können die überzähligen Stabkräfte
 * zugewiesen werden.
 * Das Programm bezweckt, die Anwendung des unteren (statischen)
 * Grenzwertsatzes der Plastizitätstheorie zu erleichtern.
 *
 * -------------------------------------------------------------
 *
 * Dieses Programm ist freie Software. Sie können es unter den Bedingungen
 * der GNU General Public License, Version 2, wie von der Free Software
 * Foundation herausgegeben, weitergeben und/oder modifizieren.
 *
 * Die Veröffentlichung dieses Programms erfolgt in der Hoffnung, dass es
 * Ihnen von Nutzen sein wird, aber OHNE JEDE GEWÄHRLEISTUNG - sogar ohne
 * die implizite Gewährleistung der MARKTREIFE oder der EIGNUNG FüR EINEN
 * BESTIMMTEN ZWECK.  Details finden Sie in der GNU General Public License.
 *
 * Sie sollten eine Kopie der GNU General Public License zusammen  mit
 * diesem Programm erhalten haben. Falls nicht, schreiben Sie an die
 * Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA. 
 */
public class clWaehlenDialog extends javax.swing.JDialog {
    
    private int was;
    String einleitung;
    boolean OK = false;
    ResourceBundle dialogRB;
    Locale locale;
    
    private static final int KNOTEN = 1;
    private static final int STAB = 2;
    
    
    /** Creates new form clWählenDialog 
     * p_was: Knoten: 1, Stab: 2*/
    public clWaehlenDialog(java.awt.Frame parent, int p_was, Locale lc) {
        super(parent, true);
        was = p_was;
        
        // übersetzen
        locale = lc;
        dialogRB = ResourceBundle.getBundle("Fachwerk/locales/gui-dialoge", locale);
        if (dialogRB == null) {
            System.err.println("FEHLER: gui-dialoge für " + locale.toString());
        }
        
        switch (was) {
            case KNOTEN:
                super.setTitle(tr("titel-KnWaehlen")); //Knoten wählen");
                einleitung = tr("KnotenWaehlen"); //Bitte einen Knoten wählen.";
                break;
            case STAB:
                super.setTitle(tr("titel-StWaehlen")); //Stab wählen");
                einleitung = tr("StabWaehlen"); //"Bitte einen Stab wählen.";
                break;
            default:
                assert false;
                
        }
        initComponents();
        übersetzen();
        tastenbelegen();
        pack();
        zentriere(parent);
        setVisible(true);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        knopfOK = new javax.swing.JButton();
        knopfAbbruch = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        feldEingabe = new javax.swing.JTextField();
        lbEinleitung = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        knopfOK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fachwerk/gui/icons/button_ok.png")));
        knopfOK.setText("OK !");
        knopfOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                knopfOKActionPerformed(evt);
            }
        });

        jPanel1.add(knopfOK);

        knopfAbbruch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fachwerk/gui/icons/button_cancel.png")));
        knopfAbbruch.setText("Abbruch");
        knopfAbbruch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                knopfAbbruchActionPerformed(evt);
            }
        });

        jPanel1.add(knopfAbbruch);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        jLabel1.setText("Nr");
        jPanel2.add(jLabel1);

        feldEingabe.setColumns(3);
        feldEingabe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feldEingabeActionPerformed(evt);
            }
        });

        jPanel2.add(feldEingabe);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        lbEinleitung.setText(einleitung);
        getContentPane().add(lbEinleitung, java.awt.BorderLayout.NORTH);

        pack();
    }//GEN-END:initComponents

    private void feldEingabeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feldEingabeActionPerformed
        OK = true;
        setVisible(false);
    }//GEN-LAST:event_feldEingabeActionPerformed

    private void knopfAbbruchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_knopfAbbruchActionPerformed
        OK = false;
        setVisible(false);
    }//GEN-LAST:event_knopfAbbruchActionPerformed

    private void knopfOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_knopfOKActionPerformed
        OK = true;
        setVisible(false);
    }//GEN-LAST:event_knopfOKActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        //dispose();
    }//GEN-LAST:event_closeDialog
    
    private void übersetzen() {
        knopfOK.setText(tr("OK"));        
        knopfAbbruch.setText(tr("Abbruch"));
        jLabel1.setText(tr("Nr"));            
    }
    
    public int getNr() {
        if (OK) {
            int nr = Fkt.holInt(feldEingabe.getText());
            return nr;
        }
        else return -1;
    }
    
    private void tastenbelegen() {
        javax.swing.ActionMap am = getRootPane().getActionMap();
        javax.swing.InputMap im = getRootPane().getInputMap(javax.swing.JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        
        // ESC - Taste
        Object EscapeObjekt = new Object();
        javax.swing.KeyStroke EscapeStroke = javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0);
        javax.swing.Action EscapeAction = new javax.swing.AbstractAction() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OK = false;
                setVisible(false);
            }
        };
        im.put(EscapeStroke, EscapeObjekt);
        am.put(EscapeObjekt, EscapeAction);
    }
    
    private void zentriere(java.awt.Frame hf) {
        java.awt.Point OL = hf.getLocationOnScreen();
        OL.translate(hf.getWidth()/2, 10);
        OL.translate(-this.getWidth()/2, 0);
        if (OL.getX() < 0) OL.setLocation(0, OL.getY());
        if (OL.getY() < 0) OL.setLocation(OL.getX(), 0);
        this.setLocation(OL);
    }
    
    private String tr(String key) {        
        String übersetzt;
        try {übersetzt = dialogRB.getString(key);}
        catch (MissingResourceException e) {
            System.err.println("Schluesselwort + " + key + " nicht gefunden fuer " + locale.toString() + " ; " + e.toString());
            return key;
        }        
        return übersetzt;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField feldEingabe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton knopfAbbruch;
    private javax.swing.JButton knopfOK;
    private javax.swing.JLabel lbEinleitung;
    // End of variables declaration//GEN-END:variables
    
}
